apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "app.name" $ }}
  labels:
    {{- include "standardLabels" $ | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "matchLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "matchLabels" $ | nindent 8 }}
      annotations:
        checksum/environment-variables: {{ include "environmentVariables" . | sha256sum }}
    spec:
      containers:
      - name: {{ template "app.name" $ }}
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.app.port }}
          protocol: TCP
        env:
        {{- include "environmentVariables" $ | nindent 8 }}
{{- if .Values.environmentVariables }}
        {{- toYaml .Values.environmentVariables | nindent 8 }}
{{- end }}
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.app.port }}
          initialDelaySeconds: 5
          periodSeconds: 15
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /metrics
            port: {{ .Values.app.port }}
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}

