{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "app.name" $ }}
  labels:
    {{- include "standardLabels" $ | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: {{ .Values.ingress.nginxProxyConnectTimeout | quote }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.ingress.nginxProxyReadTimeout  | quote }}
    nginx.ingress.kubernetes.io/proxy-send-timeout: {{ .Values.ingress.nginxProxySendTimeout | quote }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.nginxProxyBodySize }}
{{- if .Values.ingress.serverAlias }}
    nginx.ingress.kubernetes.io/server-alias: {{ .Values.ingress.serverAlias }}
{{- end }}
spec:
  rules:
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ template "app.name" $ }}
            port:
              number: {{ .Values.service.port }}
{{- else }}
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "app.name" $ }}
          servicePort: {{ .Values.service.port }}
{{- end }}
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.cert }}
