---
apiVersion: elliottmgmt.com/v1
kind: ThycoticSecret
metadata:
  name: database-config
spec:
  thycotic:
    secret_id: {{ .Values.secrets.database }}
    fields:
      - Username
      - Password
    secret:
      keys:
        POSTGRES_USERNAME: Username
        POSTGRES_PASSWORD: Password

---
apiVersion: elliottmgmt.com/v1
kind: ThycoticSecret
metadata:
  name: k8s-ca-data
spec:
  thycotic:
    secret_id: {{ .Values.secrets.k8s_ca_data }}
    fields:
      - PublicKey
    secret:
      keys:
        K8S_CA_DATA: PublicKey

---
apiVersion: elliottmgmt.com/v1
kind: ThycoticSecret
metadata:
  name: bitbucket-api-token
spec:
  thycotic:
    secret_id: {{ .Values.secrets.bitbucket_api_token }}
    fields:
      - ClientSecret 
    secret:
      keys:
        BITBUCKET_API_TOKEN: ClientSecret
