replicaCount: 1

env: dev
nameOverride: backstage

image:
  name: artifactory.elliottmgmt.com/docker-elliott-core/backstage/backstage
  tag: "default"
  pullPolicy: Always

labels:
  partOf: missionctl

app:
  logLevel: info
  port: 7007

ingress:
  host: backstage.kube-dev-cs-1.elliottmgmt.com
  serverAlias: backstage.elliottmgmt.com
  cert: kube-wildcard
  nginxProxyConnectTimeout: 600
  nginxProxyReadTimeout: 600
  nginxProxySendTimeout: 600
  nginxProxyBodySize: 30m

service:
  port: 80

resources:
  requests:
    cpu: 250m
    memory: 400Mi
  limits:
    cpu: 250m
    memory: 400Mi

monitoring:
  namespace: playground-infra
  prometheusInstance: playground
  prometheusRules: []
  grafanaDashboards: []
  serviceMonitor:
    enabled: false

affinity:

tolerations:

secrets:
  database: 9322
  k8s_ca_data: 9323
  bitbucket_api_token: 9324

environmentVariables:
  - name: JAEGER_AGENT_HOST
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: database-config
        key: Password
        optional: false
  - name: POSTGRES_USERNAME
    valueFrom:
      secretKeyRef:
        name: database-config
        key: Username
        optional: false
  - name: K8S_CA_DATA
    valueFrom:
      secretKeyRef:
        name: k8s-ca-data
        key: PublicKey
        optional: false

